export const MAJOR_ARCANA = [
  {
    id: 0,
    name: "The Fool",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/6b32dd0f5_generated_image.png",
    keywords: ["New beginnings", "Innocence", "Spontaneity", "Adventure", "Leap of faith"],
    meaning: `Something new is beginning — and it's asking you to trust it even though you can't see how it plays out. The Fool isn't reckless; The Fool is brave enough to start before being ready. You have everything you need. Stop waiting for the perfect moment. Say yes to the thing that scares you in the best way. Life is signaling a fresh chapter, a new adventure, a leap of faith that's been sitting on your heart. Take it.`,
    reversed: `You're either jumping in without thinking — ignoring red flags, rushing past your own wisdom — or you've gotten so afraid of making the wrong move that you've stopped moving at all. Fear is dressed up as caution right now. Check in: is this restraint, or is this avoidance? You don't need all the answers. But you do need to be honest about what's actually holding you back.`,
    element: "Air",
    planet: "Uranus",
    archetype: "The Divine Child / The Wanderer",
    affirmation: "I trust the unknown and step forward with open-hearted courage.",
  },
  {
    id: 1,
    name: "The Magician",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/18121c1cc_generated_image.png",
    keywords: ["Willpower", "Manifestation", "Resourcefulness", "Skill", "Focused intention"],
    meaning: `You already have everything you need to make this happen. Stop saying you're not ready. The Magician is the "I can figure this out" energy — resourceful, focused, magnetic. This is a green light. Your idea isn't crazy. Your dream isn't too big. Put your skills to work, align what you say with what you do, and watch things start to shift. The only thing between where you are and where you want to be is deliberate action.`,
    reversed: `Something's off — either you're spinning your wheels with no follow-through, or you're letting self-doubt convince you that your gifts aren't worth using. There may also be some manipulation happening — yours or someone else's. The Magician reversed says: stop overcomplicating, stop stalling, stop the games. Get honest about what you actually want and go after it the right way.`,
    element: "Air",
    planet: "Mercury",
    archetype: "The Alchemist / The Creator",
    affirmation: "I channel the energy of the universe through focused, purposeful action.",
  },
  {
    id: 2,
    name: "The High Priestess",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/58fb1d7c1_generated_image.png",
    keywords: ["Intuition", "Sacred knowledge", "Inner knowing", "Mystery", "The subconscious"],
    meaning: `You already know. That's what this card is saying. You've been asking everyone else what to do, polling opinions, researching endlessly — but the answer is already sitting quietly inside you, waiting for you to stop drowning it out with noise. Trust your gut on this one. Not everything can be Googled or rationalized. Some truths arrive through feeling, not thinking. Get quiet. Listen.`,
    reversed: `You're overriding your intuition — talking yourself out of what you feel because it doesn't make logical sense, or because someone else's voice is louder than yours right now. There may be something hidden that you're not being told, or something you're not being honest with yourself about. Come back to your own knowing. The anxiety you're feeling may actually be intuition trying to get your attention.`,
    element: "Water",
    planet: "Moon",
    archetype: "The Oracle / The Seer",
    affirmation: "I trust my inner knowing. The answers I seek already live within me.",
  },
  {
    id: 3,
    name: "The Empress",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/6220d890f_generated_image.png",
    keywords: ["Fertility", "Abundance", "Sensuality", "Nature", "Nurturing", "Creative flow"],
    meaning: `This is abundance energy. The Empress shows up when life wants you to slow down and actually receive what's around you — beauty, pleasure, creativity, love. You're allowed to enjoy this. You don't have to earn everything through struggle. This is also a powerful creative period: ideas are fertile, projects can bloom, relationships can deepen. Tend to yourself the way you'd tend to a garden. Water yourself. Give yourself room to grow.`,
    reversed: `You're running on empty and probably have been for a while. You might be over-giving, over-working, neglecting your own needs to take care of everyone else's. Or you're creatively blocked — the well has run dry because you haven't been filling it. This is a serious nudge to rest. To eat well. To do something just because it feels good. You cannot pour from empty.`,
    element: "Earth",
    planet: "Venus",
    archetype: "The Great Mother / The Creatrix",
    affirmation: "I am fertile with possibility. Life flows through me in abundance and beauty.",
  },
  {
    id: 4,
    name: "The Emperor",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/7e0f5e50d_generated_image.png",
    keywords: ["Authority", "Structure", "Stability", "Logic", "Fatherhood", "Leadership"],
    meaning: `It's time to get serious. The Emperor is structure, discipline, and showing up consistently — not because you feel like it, but because you've decided to. Whether it's finances, a project, your health, or your boundaries — this card is asking you to lead. Stop waiting for someone else to handle it. You are the authority in your own life. Build something solid. Get organized. Set the standard.`,
    reversed: `There's a power struggle somewhere — maybe with someone who's controlling or rigid, maybe with yourself. Either you're bulldozing people to get your way, or you're letting others walk all over you because you haven't claimed your own authority. The Emperor reversed also shows up when discipline has completely collapsed — plans started and abandoned, boundaries set and immediately broken. Pick a lane and hold it.`,
    element: "Fire",
    planet: "Aries (Mars)",
    archetype: "The Father / The Sovereign",
    affirmation: "I lead from a place of strength, wisdom, and compassionate authority.",
  },
  {
    id: 5,
    name: "The Hierophant",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/56b97bdc8_generated_image.png",
    keywords: ["Tradition", "Spiritual guidance", "Institutions", "Community", "Belief systems", "Ritual"],
    meaning: `The Hierophant sits between two pillars wearing ornate ceremonial vestments, his hand raised in a gesture of blessing. Before him kneel two figures seeking spiritual instruction. He is the bridge between the sacred and the mundane, the keeper of traditional wisdom and established systems of belief. This card represents organized religion, formal education, cultural traditions, and the wisdom that has been passed down through generations. When The Hierophant appears, there may be value in following a more conventional path, seeking a teacher or mentor, or engaging with a community of shared belief. This card invites you to explore structured spiritual practice — rituals, ceremonies, and ancient wisdom — as a source of grounding and guidance. There is deep power in tradition when it is approached with conscious intention.`,
    reversed: `The Hierophant reversed is the energy of the reformer, the questioner, the one who refuses to follow a path simply because it has always been done that way. It can signal a time to break free from dogma, rigid belief systems, or societal expectations that no longer serve your authentic self. You may be experiencing a clash with institutional authority or feeling suffocated by convention. This reversal can also warn of blind faith — following teachings without discernment. Trust your own spiritual authority. It's time to write new rules.`,
    element: "Earth",
    planet: "Taurus (Venus)",
    archetype: "The Spiritual Teacher / The Traditionalist",
    affirmation: "I honor the wisdom of tradition while following my own authentic spiritual path.",
  },
  {
    id: 6,
    name: "The Lovers",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/37f6bb2ad_generated_image.png",
    keywords: ["Love", "Alignment", "Choice", "Harmony", "Union", "Values"],
    meaning: `A choice is in front of you — and it might not be about romance at all. The Lovers is about alignment: choosing what actually matches your values versus what looks good, feels safe, or is expected of you. When this card appears, you're at a fork. The path that aligns with your truest self might also be the harder one. But choosing out of fear or obligation always costs more in the long run. What do you actually want?`,
    reversed: `Something's misaligned — you might be in a relationship, job, or situation that looks fine on paper but doesn't feel right in your gut. Or you're avoiding making a choice that you know needs to be made. The Lovers reversed can also mean you're disconnected from yourself, seeking connection with others while skipping the most important relationship: the one you have with you. Get honest about what you're actually choosing and why.`,
    element: "Air",
    planet: "Gemini (Mercury)",
    archetype: "The Beloved / The Chooser",
    affirmation: "I choose in alignment with my truest values, and love flows freely from that honesty.",
  },
  {
    id: 7,
    name: "The Chariot",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/6c41b88c6_generated_image.png",
    keywords: ["Victory", "Willpower", "Determination", "Control", "Direction", "Triumph"],
    meaning: `The Chariot depicts a warrior riding a chariot pulled by two sphinxes — one black, one white. They represent opposing forces: instinct and intellect, fear and courage, darkness and light. The warrior does not hold reins to control them; instead he exercises sheer focused will. Above his head is a canopy of stars. This is a card of triumph through discipline and directed force. When The Chariot appears, you are being called to take command of your inner forces — to stop letting conflicting desires, fears, or impulses pull you in opposite directions. Victory is yours, but it requires focus, determination, and the willingness to move boldly through obstacles. This is not a passive card. It demands that you take the wheel of your own life and drive with confidence. Success will come through concentrated willpower.`,
    reversed: `The Chariot reversed signals a loss of direction and control — not external events pulling the rug from under you, but an internal collapse of willpower. You may feel scattered, overwhelmed, or stuck. The opposing forces within you — your fears and your ambitions, your logic and your emotions — may be warring against each other, leaving you paralyzed. There is also a warning against aggression and forcing your will onto others or onto situations that require a softer touch. Surrender what you cannot control. Focus only on what you can. Reclaim your inner compass.`,
    element: "Water",
    planet: "Cancer (Moon)",
    archetype: "The Warrior / The Victor",
    affirmation: "I direct my will with clarity and confidence, moving through obstacles with grace.",
  },
  {
    id: 8,
    name: "Strength",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/a9903bcf9_generated_image.png",
    keywords: ["Courage", "Inner strength", "Compassion", "Patience", "Taming the beast"],
    meaning: `You're stronger than you're giving yourself credit for — and this card is proof. Strength isn't about forcing or fighting; it's about the quiet, steady confidence that handles hard things without falling apart. You can face whatever this is. You don't need to white-knuckle it. Meet it with patience and self-compassion. The lion tamed by gentleness, not brute force — that's the energy here. You've got this.`,
    reversed: `You're either doubting yourself to the point of paralysis, or you're letting your emotions run the show — reacting from the raw, unfiltered place instead of the steady, grounded one. Check in: are you avoiding something difficult because you don't believe you can handle it? You can. Or are you exploding at things that deserve a softer approach? Either way, the answer is the same: come back to yourself. Be gentle first.`,
    element: "Fire",
    planet: "Leo (Sun)",
    archetype: "The Gentle Warrior",
    affirmation: "My greatest strength is the compassion and courage I show in the face of challenge.",
  },
  {
    id: 9,
    name: "The Hermit",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/2fc6fbf29_generated_image.png",
    keywords: ["Solitude", "Soul-searching", "Introspection", "Inner guidance", "Wisdom"],
    meaning: `It's time to get quiet. The Hermit shows up when the answer you're looking for can't be found by asking more people or scrolling more content — it's found in stillness. Take yourself off the grid for a bit. Journal. Walk alone. Sit with yourself without distraction. This isn't antisocial; it's necessary. The wisdom you need right now is already inside you, but you won't hear it until you stop drowning it out.`,
    reversed: `You're either isolating in an unhealthy way — cutting off connection, shutting people out — or you're doing the opposite: constantly seeking external noise and company to avoid the uncomfortable quiet inside. Either end of that spectrum points to the same thing: there's something within you that you're not ready to face yet. You don't have to dive in all at once. But five minutes of honest quiet a day is a start.`,
    element: "Earth",
    planet: "Virgo (Mercury)",
    archetype: "The Wise Elder / The Seeker",
    affirmation: "I honor the sacred gift of solitude and trust the wisdom that lives in silence.",
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/e67a90405_generated_image.png",
    keywords: ["Cycles", "Karma", "Destiny", "Turning points", "Luck", "Change"],
    meaning: `Things are shifting — and in your favor. The Wheel of Fortune is a turning point: circumstances that felt stuck are starting to move, opportunities are opening, the tide is changing. This is also a karma card — what you've been putting out is starting to come back. If you've been doing the work, showing up, and acting with integrity, this is your payoff. Change is here. Ride it.`,
    reversed: `A rough patch. Things feel like they keep going wrong or like you're stuck in a cycle you can't break. The Wheel reversed asks you to look at your patterns — what keeps repeating? What lesson keeps showing up in different costumes? You're not a victim of fate, but you might be a victim of habit. Notice the cycle. Name it. That's the first step to breaking it.`,
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Wheel / Fate",
    affirmation: "I trust the cycles of my life, knowing that every turn of the wheel brings growth and renewal.",
  },
  {
    id: 11,
    name: "Justice",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/70785ea2b_generated_image.png",
    keywords: ["Truth", "Fairness", "Law", "Accountability", "Balance", "Cause and effect"],
    meaning: `What you put out, you get back. Justice is the karma card — and right now the universe is balancing the scales. If you've been doing right, doing the work, showing up with integrity — this card is good news. If there's a situation that's been unfair, resolution is coming. It also asks you to be honest about your own role in any conflict. Not to blame yourself, but to see clearly. Truth is always the path forward here.`,
    reversed: `Something isn't fair — and it might not get resolved the way you think it should. Or you're avoiding accountability for your part in something. Justice reversed asks you to get honest, even if it's uncomfortable: are you telling the full story, including your role? It can also show up when you're being way too hard on yourself — judging yourself by a standard you wouldn't apply to anyone else. Truth cuts both ways.`,
    element: "Air",
    planet: "Libra (Venus)",
    archetype: "The Judge / The Witness",
    affirmation: "I walk in integrity, knowing that truth and fairness are the foundation of my path.",
  },
  {
    id: 12,
    name: "The Hanged One",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/84c6df43d_generated_image.png",
    keywords: ["Surrender", "Pause", "New perspective", "Sacrifice", "Letting go", "Suspension"],
    meaning: `Stop. Just — stop. The Hanged One is a card of sacred pause: the universe is asking you to wait, to surrender the timeline, to stop pushing and start seeing. This delay is not punishment; it's preparation. Something needs to shift in how you're looking at this situation before the right move becomes clear. Trying to force it right now will backfire. The surrender is the work. What becomes possible when you stop fighting?`,
    reversed: `You're fighting the pause — pushing, forcing, getting more frustrated that things aren't moving faster. Or you've swung to the other extreme: using "I'm just waiting for the right time" as a way to avoid ever actually acting. The Hanged One reversed asks: is this surrender or stalling? Is this wisdom or avoidance? Be honest. The suspension has gone on long enough. It's time to choose.`,
    element: "Water",
    planet: "Neptune",
    archetype: "The Mystic / The Willing Sacrifice",
    affirmation: "I release my grip and trust that in surrender, a new and profound wisdom is revealed.",
  },
  {
    id: 13,
    name: "Death",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/94fb17882_generated_image.png",
    keywords: ["Endings", "Transformation", "Transition", "Release", "Rebirth", "Change"],
    meaning: `Not literal death — don't panic. This card is about endings that are necessary for something new to begin. A chapter is closing. A relationship, a version of yourself, a way of doing things that simply doesn't fit anymore. You might be grieving it, and that's okay. But you can't drag the past into the future and expect things to change. Something has to end for something better to arrive. Let it end.`,
    reversed: `You're holding on to something that's already over — a relationship that's run its course, a belief that no longer fits, a version of your life you've outgrown. The fear of the unknown is keeping you stuck in something that isn't actually working. Or there's a transformation happening under the surface that you're not quite ready to acknowledge yet. Either way: the old way isn't coming back. The sooner you accept that, the sooner you can move.`,
    element: "Water",
    planet: "Scorpio (Pluto)",
    archetype: "The Transformer / The Liberator",
    affirmation: "I release what has ended with grace, trusting that every ending carries the seed of a new beginning.",
  },
  {
    id: 14,
    name: "Temperance",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/3d4272059_generated_image.png",
    keywords: ["Balance", "Patience", "Moderation", "Purpose", "Flow", "Alchemy"],
    meaning: `Slow down and find the middle ground. Temperance is balance, patience, and the art of not going to extremes. Something in your life needs recalibrating — maybe you've been overdoing it in one direction and neglecting another. This card asks you to blend, to integrate, to let things come together at the pace they need rather than forcing it. The right formula requires time and intention. Don't rush the mix.`,
    reversed: `You're off balance — burning the candle at both ends, swinging between extremes, making impulsive decisions that feel good for five minutes and messy for weeks. Temperance reversed says: this pace is not sustainable. Something needs to give. Identify what you're overdoing and what you're neglecting. The goal isn't perfection — it's just a little more equilibrium than you have right now.`,
    element: "Fire",
    planet: "Sagittarius (Jupiter)",
    archetype: "The Alchemist / The Healer",
    affirmation: "I move through life with patience and grace, blending all parts of myself into wholeness.",
  },
  {
    id: 15,
    name: "The Devil",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/9b549509a_generated_image.png",
    keywords: ["Shadow self", "Bondage", "Addiction", "Materialism", "Illusion", "Attachment"],
    meaning: `Something has a hold on you — and you probably already know what it is. The Devil isn't about evil; it's about the patterns, habits, relationships, or thought loops that keep you trapped. Here's the thing: the chains in this card are loose. You could leave. You could stop. You're choosing not to, for reasons worth examining. What are you getting out of staying stuck? What would you have to face if you actually let this go?`,
    reversed: `You're breaking free — or you're about to. Something that had power over you is losing its grip. A pattern you've been stuck in is becoming visible enough to actually change. The Devil reversed is liberation in progress. It can also be a warning that a habit or situation is escalating — getting darker, not lighter. Check in honestly: is this getting better, or worse? The exit is still available either way.`,
    element: "Earth",
    planet: "Capricorn (Saturn)",
    archetype: "The Shadow / The Tempter",
    affirmation: "I am free. I choose to release every chain that binds me and step into my sovereign power.",
  },
  {
    id: 16,
    name: "The Tower",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/79788212d_generated_image.png",
    keywords: ["Sudden change", "Upheaval", "Revelation", "Chaos", "Liberation", "Awakening"],
    meaning: `Something is about to break open — and it probably needs to. The Tower is the sudden shake-up that exposes what was never built on solid ground. It's uncomfortable, sometimes shocking, but it's also clarifying. Whatever falls apart wasn't meant to hold. This isn't punishment. This is the universe refusing to let you stay in something that was slowly suffocating you. Once the dust settles, you'll have room to build something real.`,
    reversed: `The collapse is either being avoided (temporarily) or happening slowly under the surface. You might feel a slow-building pressure — a situation that keeps getting harder to sustain but that you haven't yet let yourself acknowledge is failing. Or you narrowly avoided a crisis and are recovering. Either way: don't rebuild the same thing. Use this moment to honestly look at what's crumbling and decide what's actually worth keeping.`,
    element: "Fire",
    planet: "Mars",
    archetype: "The Destroyer / The Liberator",
    affirmation: "I welcome necessary destruction, knowing that what falls was never truly mine to keep.",
  },
  {
    id: 17,
    name: "The Star",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/3b8a60757_generated_image.png",
    keywords: ["Hope", "Renewal", "Faith", "Inspiration", "Healing", "Serenity"],
    meaning: `After something hard, this card shows up to say: you're going to be okay. More than okay. The Star is healing, hope, and the quiet knowing that things are getting better even when you can't fully see it yet. Let yourself rest. Let yourself be cared for. Stop bracing for the next hit. This is a genuinely good moment — one that asks you to be open enough to receive it. The worst is behind you.`,
    reversed: `You're having a hard time believing things will get better — and honestly, that's understandable. But The Star reversed asks you not to let cynicism or exhaustion close you off to healing that's actually available to you right now. Someone wants to help. Something good is trying to reach you. Let it. Hope isn't weakness. It's the thing that keeps you moving when nothing else does.`,
    element: "Air",
    planet: "Aquarius (Uranus)",
    archetype: "The Healer / The Dreamer",
    affirmation: "I am renewed. Hope flows through me, and I trust in the healing power of the universe.",
  },
  {
    id: 18,
    name: "The Moon",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/05c76072e_generated_image.png",
    keywords: ["Illusion", "Fear", "The unconscious", "Dreams", "Deception", "Cycles"],
    meaning: `Things are murky right now — and you're probably not seeing the full picture. The Moon is the card of illusion, anxiety, and the fears that show up at 3am and feel completely real. Something is hidden, either from you or within you. Don't make big decisions from this foggy state. Sit with the uncertainty. Pay attention to dreams and gut feelings rather than anxious thoughts. What you're afraid of may not actually be as threatening as it feels.`,
    reversed: `The fog is starting to lift. Something that's been confusing or hidden is becoming clearer. A fear that had power over you is losing its grip. This is also a card of confronting what you've been avoiding — the thing you keep pushing down keeps coming up, and this time it's worth facing it directly. Clarity is on the other side of the discomfort.`,
    element: "Water",
    planet: "Pisces (Neptune)",
    archetype: "The Dreamer / The Shadow Walker",
    affirmation: "I walk through uncertainty with trust, knowing my intuition lights the path through the dark.",
  },
  {
    id: 19,
    name: "The Sun",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/237d5b7ca_generated_image.png",
    keywords: ["Joy", "Vitality", "Success", "Clarity", "Abundance", "Radiance"],
    meaning: `Yes. This is genuinely good. The Sun is the best card in the deck — success, joy, clarity, things going right. Stop waiting for the catch. Stop bracing for it to fall apart. This is a card that says: receive this. Celebrate. Let yourself be happy. Your energy is magnetic right now, things are clicking into place, and the path forward is clear. Go enjoy your life.`,
    reversed: `You're blocking your own joy — either through self-doubt, negative self-talk, or refusing to believe that good things can actually last. The Sun reversed doesn't mean things are bad; it means you're having trouble letting yourself experience how good they could be. Something — or someone — may also be dimming your light. Check in: what are you doing to dim yourself? What would it look like to actually shine?`,
    element: "Fire",
    planet: "Sun",
    archetype: "The Child / The Joyful Self",
    affirmation: "I radiate joy and vitality. My authentic light illuminates the world around me.",
  },
  {
    id: 20,
    name: "Judgement",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/7347ce2b0_generated_image.png",
    keywords: ["Rebirth", "Awakening", "Reckoning", "Calling", "Absolution", "Transformation"],
    meaning: `You're being called to level up — and you can feel it. Judgement is the wake-up call, the moment you stop pretending not to know what you know, stop playing small, and step into a version of yourself that's been waiting. This card shows up when a major reckoning or decision point arrives: not to punish, but to clarify. The past has prepared you. What are you finally ready to become?`,
    reversed: `You're ignoring the call. Something in you knows it's time to make a move — to leave, to commit, to speak up, to change — and you keep finding reasons to wait. The Judgement reversed also shows up when you're drowning in self-blame or shame over something past. It wasn't meant to be a life sentence. Forgive yourself, learn what you can, and move. The call isn't going away.`,
    element: "Fire",
    planet: "Pluto",
    archetype: "The Awakener / The Risen",
    affirmation: "I answer my soul's calling with courage, rising renewed from the ashes of who I used to be.",
  },
  {
    id: 21,
    name: "The World",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/85c67e0c3_generated_image.png",
    keywords: ["Completion", "Wholeness", "Integration", "Accomplishment", "Fulfillment", "Cosmic unity"],
    meaning: `You made it. Something has genuinely completed — a cycle, a chapter, a long and difficult season of growth — and you're being asked to stop and actually feel that. Take the win. Honor how far you've come. The World is wholeness: all the pieces coming together, the satisfaction of something fully lived. And after the celebration? A new beginning. But first — pause. Acknowledge this. You earned it.`,
    reversed: `Almost, but not quite. There's something unfinished — a project, a conversation, a chapter you're dragging out instead of closing properly. The World reversed says: tie the loose end. Finish the thing. The reason it feels hard to complete might be fear of what comes next, or grief about letting something go. But incompletion keeps you stuck. Give it the ending it deserves.`,
    element: "Earth",
    planet: "Saturn",
    archetype: "The Cosmic Dancer / The Whole Self",
    affirmation: "I stand in the fullness of who I am, celebrating the wholeness of my journey.",
  },
];

export const SPREADS = {
  single: { name: "Single Card", count: 1, positions: ["Your Message"], premium: false },
  three_card: { name: "Past, Present, Future", count: 3, positions: ["Past", "Present", "Future"], premium: false },
  universe_mic: { name: "Universe Has the Mic", count: 3, positions: ["The Mirror", "The Noise", "The Truth"], premium: false },
  heart_recovery: { name: "Heart Recovery", count: 4, positions: ["What Broke", "What's Healing", "How to Love Yourself Today", "Your Future Strength"], premium: false, selflove: true },
  boundary_builder: { name: "Boundary Builder", count: 3, positions: ["Where You're Over-Extending", "Who Is Draining You", "How to Say No & Mean It"], premium: false, selflove: true },
  career: { name: "Career Path", count: 4, positions: ["Where You Are Now", "What's Blocking You", "Your Untapped Strength", "Next Right Move"], premium: false },
  money: { name: "Money & Abundance", count: 3, positions: ["Your Money Story", "What's Blocking Flow", "How to Invite Abundance"], premium: false },
  life_path: { name: "Life Path", count: 5, positions: ["Your Soul's Purpose", "Current Lesson", "What to Release", "What to Embrace", "Your Destination"], premium: true },
  celtic_cross: { name: "Celtic Cross", count: 10, positions: ["Present", "Challenge", "Past", "Future", "Above", "Below", "Advice", "External", "Hopes", "Outcome"], premium: true },
  shadow_work: { name: "Shadow Work", count: 5, positions: ["Your Shadow", "Root Cause", "How It Manifests", "Lesson", "Integration"], premium: true },
  crossroads: { name: "The Crossroads", count: 3, positions: ["Path A", "Path B", "Decision Point"], premium: false, description: "Two paths diverge — which one is calling you, and what's the real decision?" },
  shadow_light: { name: "Shadow & Light", count: 2, positions: ["What Is Hidden", "What Is Revealed"], premium: false, description: "What's lurking beneath the surface and what's ready to be seen." },
  spiritual_alignment: { name: "Spiritual Alignment", count: 4, positions: ["Mind", "Body", "Spirit", "Divine Advice"], premium: true, description: "A full-spectrum check-in across your four layers of being." },
};

// Love-specific spreads (used on the Love page)
export const LOVE_SPREADS = {
  their_perspective: {
    name: "Their Perspective",
    count: 5,
    positions: ["How They See You", "Their Hidden Feelings", "What They Want to Say", "What's Holding Them Back", "Where This Is Going"],
    premium: false,
    channeled: true,
    description: "See the situation through their eyes — what they feel, what they hide, and where this is going.",
  },
  will_they_reach_out: {
    name: "Will They Reach Out?",
    count: 3,
    positions: ["Their Current Energy", "What's Stopping Them", "The Likely Outcome"],
    premium: false,
    channeled: false,
    description: "The cards tell you where their head is at and whether contact is coming.",
  },
  love_path: {
    name: "Where Is This Going?",
    count: 4,
    positions: ["Where You Both Stand Now", "The Hidden Obstacle", "What Needs to Happen", "The Destination"],
    premium: false,
    channeled: false,
    description: "A clear-eyed look at where this connection is truly headed.",
  },
  reconciliation: {
    name: "Should I Go Back?",
    count: 5,
    positions: ["Why It Ended", "What Has Actually Changed", "Their True Feelings Now", "What Returning Would Cost You", "The Honest Answer"],
    premium: false,
    channeled: false,
    description: "The truth about going back — no sugarcoating, no false hope.",
  },
  new_love: {
    name: "Is This the One?",
    count: 4,
    positions: ["Their True Character", "What They're Bringing Into Your Life", "The Red Flag to Watch", "The Potential"],
    premium: false,
    channeled: false,
    description: "A soul-level look at this new connection — the good, the real, and the potential.",
  },
  twin_flame: {
    name: "Twin Flame / Soulmate",
    count: 6,
    positions: ["The Soul Contract", "Your Lesson", "Their Lesson", "What's Being Healed", "The Divine Timing", "What You Both Need to Surrender"],
    premium: true,
    channeled: false,
    description: "A deep dive into your karmic and spiritual connection.",
  },
  message_from_them: {
    name: "Message From Them",
    count: 3,
    positions: ["What's on Their Heart", "What They Can't Say Out Loud", "The Message They're Sending You Energetically"],
    premium: false,
    channeled: true,
    isMessage: true,
    description: "What are they really feeling and trying to communicate — even if they haven't said a word.",
  },
};

export const ZODIAC_SIGNS = [
  { sign: "aries", symbol: "♈", element: "Fire", dates: "Mar 21 - Apr 19" },
  { sign: "taurus", symbol: "♉", element: "Earth", dates: "Apr 20 - May 20" },
  { sign: "gemini", symbol: "♊", element: "Air", dates: "May 21 - Jun 20" },
  { sign: "cancer", symbol: "♋", element: "Water", dates: "Jun 21 - Jul 22" },
  { sign: "leo", symbol: "♌", element: "Fire", dates: "Jul 23 - Aug 22" },
  { sign: "virgo", symbol: "♍", element: "Earth", dates: "Aug 23 - Sep 22" },
  { sign: "libra", symbol: "♎", element: "Air", dates: "Sep 23 - Oct 22" },
  { sign: "scorpio", symbol: "♏", element: "Water", dates: "Oct 23 - Nov 21" },
  { sign: "sagittarius", symbol: "♐", element: "Fire", dates: "Nov 22 - Dec 21" },
  { sign: "capricorn", symbol: "♑", element: "Earth", dates: "Dec 22 - Jan 19" },
  { sign: "aquarius", symbol: "♒", element: "Air", dates: "Jan 20 - Feb 18" },
  { sign: "pisces", symbol: "♓", element: "Water", dates: "Feb 19 - Mar 20" },
];

export const ORACLE_CARDS = [
  {
    id: 1,
    name: "Inner Light",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/30d1e36ec_generated_image.png",
    keywords: ["Illumination", "Self-knowledge", "Radiance", "Truth"],
    meaning: `You've been searching outward — for someone to confirm you, a sign to reassure you, a circumstance to finally make you feel whole. Stop. The light you've been chasing is already burning inside you, steadier than anything the external world could ever offer. This card lands in your reading today because you are being called back to yourself — to the part of you that doesn't need permission, doesn't need applause, and doesn't dim to make others comfortable. Your inner light isn't a metaphor. It is a force. And right now, the universe is asking you to stop hiding it. Whatever you've been second-guessing, whatever voice inside you has been quietly saying *this is right* — trust it. The lamp has always been lit. You simply forgot to look inward.`,
    affirmation: "My inner light is constant, unshakeable, and more than enough.",
  },
  {
    id: 2,
    name: "The Phoenix",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/0c43212b2_generated_image.png",
    keywords: ["Rebirth", "Resurrection", "Rising", "Courage"],
    meaning: `You've been in the fire. Maybe you're still in it. What you need to know is this: the burning is not punishment — it is alchemy. The Phoenix does not survive the flames. The Phoenix *becomes* through them. Everything that is falling away right now — the identity, the relationship, the version of yourself you thought you'd be — it is not loss. It is fuel. You are being remade at a cellular level, reshaped by heat into something that could not have existed before this moment. The hardest part isn't the falling apart. The hardest part is trusting that rising is possible. It is. You've done it before, even if you don't remember. And this time, you rise differently — with the full knowledge of what you survived.`,
    affirmation: "I rise. Every ending is the first breath of something extraordinary.",
  },
  {
    id: 3,
    name: "Sacred Feminine",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/96d58b0d1_generated_image.png",
    keywords: ["Intuition", "Receptivity", "Cyclical wisdom", "Embodiment"],
    meaning: `There is a part of you that knows things before they can be explained — that reads the room before a word is spoken, that feels the shift in energy before the news arrives. This is the sacred feminine within you, and it does not belong to any gender. It belongs to all who are willing to slow down enough to listen. Right now you are being asked to stop pushing and start receiving. To honor your cycles — the high-energy days and the ones where you need to withdraw and restore. To trust the body's knowing over the mind's noise. Something is being offered to you not through effort but through openness. Can you soften enough to let it in? The sacred feminine is not passive. She is the deep water — and deep water is the most powerful force on earth.`,
    affirmation: "I trust the wisdom of my body, my cycles, and the quiet knowing beneath thought.",
  },
  {
    id: 4,
    name: "Unbreakable",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/af1529a0f_generated_image.png",
    keywords: ["Resilience", "Core strength", "Endurance", "Sovereignty"],
    meaning: `You think you're fragile. You're not. Look back at every moment you swore you couldn't make it through — and then count how many of them you made it through anyway. This card is not here to tell you life won't be hard. It will be. It already has been. What this card is here to tell you is that there is something in you that does not break. It bends. It grieves. It howls at the moon on the worst nights. But it does not shatter. That is not weakness wearing the mask of strength — that is the real thing. Unbreakable doesn't mean you feel no pain. It means the pain doesn't get the final word. Whatever is being tested in you right now — your patience, your faith, your sense of self — you are more than equal to it. You have always been.`,
    affirmation: "I am built from everything I have survived. I am unbreakable at my core.",
  },
  {
    id: 5,
    name: "The Void",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/c465687cc_generated_image.png",
    keywords: ["Emptiness", "Potential", "The unknown", "Gestation"],
    meaning: `You are standing in the space between what was and what will be, and it feels like nothing — like you've lost your footing, your identity, your map. This is The Void. And before you try to fill it, rush through it, or numb your way out of it, consider this: the void is not nothing. The void is *everything before form*. Every universe begins in darkness. Every seed germinates in the invisible underground before it ever breaks into light. You are in a sacred gestation right now. The discomfort you feel is not absence — it is potential that hasn't yet found its shape. Do not force it. Do not perform a version of yourself that you no longer are. Sit in the not-knowing. Something is being composed in the dark, and it will be unlike anything you have made before.`,
    affirmation: "I rest in the space of possibility. From emptiness, everything is born.",
  },
  {
    id: 6,
    name: "Ancestor Wisdom",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/dbfced5fd_generated_image.png",
    keywords: ["Lineage", "Inherited gifts", "Ancestral healing", "Roots"],
    meaning: `You did not arrive here alone. Behind you stands a line of people who survived things that should have broken them — wars, migrations, losses so enormous they had no words for them. And yet they lived. They loved. They made it far enough forward that you exist. This card arrives to remind you of that inheritance — not the wounds alone, but the wisdom, the resilience, the gifts encoded in your very cells. You may also be called right now to do the healing your ancestors could not: to feel what they suppressed, to speak what they silenced, to choose differently where they had no choice. This is not burden. This is sacred work. When you heal yourself, ripples travel both backward and forward in time. Your healing is their peace. Your wholeness is their gift.`,
    affirmation: "I carry the wisdom of my ancestors. I heal for myself and for all who came before.",
  },
  {
    id: 7,
    name: "Synchronicity",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/690755872_generated_image.png",
    keywords: ["Signs", "Alignment", "Meaningful coincidence", "Flow"],
    meaning: `You've been noticing things — numbers that repeat, names that keep appearing, a song that plays at exactly the right moment, a stranger who says exactly what you needed to hear. This is not coincidence. The universe does not waste its breath on random noise. Synchronicity is the language the cosmos speaks when it wants your attention, when it wants to confirm: *you are on the right path*. The question isn't whether the signs are real — they are. The question is whether you are willing to trust them over the anxious voice that says it's all just chance. Pay attention to what keeps crossing your field of vision this week. The pattern you're seeing is not your imagination. It is an invitation. Follow the breadcrumbs.`,
    affirmation: "I am awake to the signs. The universe speaks and I am listening.",
  },
  {
    id: 8,
    name: "The Mirror",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/6f50831cc_generated_image.png",
    keywords: ["Reflection", "Projection", "Self-awareness", "Truth"],
    meaning: `What is irritating you most about someone else right now? What in another person makes you recoil, feel threatened, or quietly furious? Look closer. The Mirror is not a comfortable card. It asks you to consider the possibility that what you see most clearly in others — both the qualities you admire and the ones you judge — are reflections of something alive in you. The person who frustrates you with their neediness may be showing you your own unmet needs. The one whose confidence unsettles you may be mirroring an unlived boldness you've been suppressing. This is not blame. It is the most radical form of self-knowledge available to you. The world is your mirror. And what it's reflecting right now contains information about where your greatest growth lies.`,
    affirmation: "Every reflection teaches me something true. I meet what I see with curiosity, not judgment.",
  },
  {
    id: 9,
    name: "Release",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/fc1b9edec_generated_image.png",
    keywords: ["Letting go", "Liberation", "Surrender", "Space"],
    meaning: `You already know what needs to go. You've known for a while. The story you keep telling about why you can't, why it's too soon, why you need just a little more time — that story is the thing that's keeping you stuck, not the circumstance itself. Release is not betrayal. Letting go of a relationship, a belief, a version of yourself, a grievance you've been nursing — none of it means you didn't care. It means you care enough about your own becoming to stop carrying what was never meant to travel this far with you. What would your life feel like if you put it down? Not someday. Today. The weight you've grown so accustomed to is not protection. It is simply weight. Put it down. Breathe. Feel how much space you have.`,
    affirmation: "I release with grace what no longer belongs in my story. Space is a gift I give myself.",
  },
  {
    id: 10,
    name: "Divine Timing",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/37d033396_generated_image.png",
    keywords: ["Patience", "Trust", "Seasons", "Sacred delay"],
    meaning: `You are not behind. That needs to be said plainly, because the anxiety running in the background of your days insists that you are — that everyone else is moving faster, arriving sooner, having it figured out while you remain suspended in the waiting. But there is no such thing as being late in the cosmic order. There is only the timing that belongs to *your* life, your specific unfolding, the exact sequence of preparation and readiness that this particular dream requires. The seed that pushes through too soon gets killed by the frost. The fruit pulled before its time is bitter. You are not stuck. You are becoming. And when the moment arrives — and it will — you will look back and understand with stunning clarity why it couldn't have come a single day sooner.`,
    affirmation: "My life unfolds in perfect timing. I trust the process completely.",
  },
  {
    id: 11,
    name: "Shadow Self",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/280d3f1d7_generated_image.png",
    keywords: ["Shadow work", "Integration", "Hidden self", "Wholeness"],
    meaning: `The part of you that you are most ashamed of — the one that wants too much, feels too fiercely, acts in ways that contradict your self-image — that part has not gone anywhere just because you stopped looking at it. Your shadow is not your enemy. It is the exiled parts of yourself that never got to be whole, the instincts and desires and wounds that were told they were too much, too dark, too inconvenient. This card appears when those exiled parts are pressing against the door. Not to destroy you, but to be integrated. The most dangerous shadow is the one left in the dark, because it acts through you without your awareness. Turn toward it. Name what you find. The strange alchemy of shadow work is this: the thing you feared most in yourself, once met with honest eyes, loses its power to control you — and sometimes becomes your greatest gift.`,
    affirmation: "I turn toward my shadow with courage. In integration, I become fully whole.",
  },
  {
    id: 12,
    name: "New Moon Intention",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/83165beef_generated_image.png",
    keywords: ["Intention", "Planting seeds", "Beginnings", "Vision"],
    meaning: `In the dark of the new moon, before any light is visible, the seed is planted. This is where you are — in the creative darkness before the manifestation, at the threshold of a cycle that hasn't yet shown its face. This card is asking you to get clear. Not about what you think you *should* want, not about what looks impressive or practical or safe — but about what your soul is genuinely reaching toward. Write it down. Speak it aloud. Hold it like something precious. Intentions planted now have tremendous energetic momentum behind them. The field is fertile. Your focus is the fertilizer. Be specific, be honest, be bold. The universe can only meet the vision you're willing to hold clearly. What are you calling in?`,
    affirmation: "I plant my intentions with clarity and faith, knowing the universe conspires in my favor.",
  },
  {
    id: 13,
    name: "The Alchemist",
    image: "https://media.base44.com/images/public/69dabcfbdff2d23eb6ddb562/b8b623458_generated_image.png",
    keywords: ["Transformation", "Mastery", "Creation", "Transmutation"],
    meaning: `The alchemist does not start with gold — they start with lead. They start with the raw, the difficult, the unrefined. And through the patient, skilled application of heat, time, and intention, they transform it into something of profound value. This is the work you are being called to right now. Not waiting for your circumstances to be ideal, not waiting until you feel ready or healed or fully formed — but beginning the sacred work of transformation with exactly what you have. The mess is the material. The difficulty is the fire. You are both the alchemist and the substance being transformed. What feels like the most stubborn, unworkable aspect of your life right now? That is your lead. That is where the gold is hiding. Touch it with mastery and intention, and watch what is made.`,
    affirmation: "I transform everything I touch. My greatest challenges are the raw materials of my mastery.",
  },
];

// ─── Unfiltered Truth Oracle — 44-card relationship deck (text-only) ───
export const UNFILTERED_TRUTH_ORACLE = [
  { id: 'ut-01', name: 'The Ghost', meaning: `They're here but not really here — showing up just enough to keep you hoping but not enough to actually show up. Ghosting isn't always disappearing. Sometimes it's staying just present enough to keep the door open while they figure out if they actually want to walk through it. The question isn't why they keep vanishing. The question is: what do YOU want to do with someone who keeps making you wonder?`, keywords: ['avoidance', 'inconsistency', 'fear of commitment', 'limbo'] },
  { id: 'ut-02', name: 'Sovereignty', meaning: `You've been giving this person your power in small ways — waiting for their text to set the mood of your day, making decisions based on what they might think, dimming yourself to make them comfortable. This card is a direct invitation to take it back. Your sovereignty is not negotiable. Your peace, your time, your emotional energy — these are not bargaining chips in someone else's story. Reclaim them. Fully. Now.`, keywords: ['personal power', 'self-authority', 'independence', 'boundaries'] },
  { id: 'ut-03', name: 'The Breadcrumbs', meaning: `You are being kept alive on the bare minimum — a text here, a reaction there, just enough to keep you invested but not enough to actually feed you. Breadcrumbs are not a meal. They are a strategy, whether conscious or not, to keep you available without committing. You deserve someone who brings the whole loaf. Stop starving and calling it a relationship.`, keywords: ['minimal effort', 'stringing along', 'inconsistency', 'low investment'] },
  { id: 'ut-04', name: 'The Mirror', meaning: `What frustrates you most about this person may be reflecting something you haven't faced in yourself — a fear of vulnerability, an old wound that says you're unworthy of consistency, a pattern you keep choosing because it feels familiar even when it hurts. Look honestly. The irritation is data. The mirror doesn't lie, even when what it shows is uncomfortable.`, keywords: ['self-reflection', 'projection', 'inner work', 'patterns'] },
  { id: 'ut-05', name: 'The Red Flag You Rationalized', meaning: `You saw it. You knew. And then you found twelve reasons why it was fine, why they didn't mean it that way, why it was your fault, why you were being too sensitive. This card is not here to shame you — it's here to name the thing you've been naming for someone else for too long. The flag was red. You are allowed to trust what you saw.`, keywords: ['denial', 'rationalization', 'gaslighting', 'clarity'] },
  { id: 'ut-06', name: 'The Situationship', meaning: `You have all the intimacy of a relationship and none of the commitment. You share their bed, their secrets, their Sunday mornings — and you have no idea where you stand. This in-between place was never meant to be permanent housing. At some point you have to decide: are you willing to name what you actually want, even if naming it means losing what you have?`, keywords: ['undefined relationship', 'ambiguity', 'avoidance', 'truth-telling'] },
  { id: 'ut-07', name: 'The Slow Fade', meaning: `Nothing dramatic happened. The conversations just got shorter. The response times got longer. The plans stopped materializing. The slow fade is one of the cruelest exits because it leaves you wondering if you imagined the whole thing. You didn't. And you deserve an ending that has actual words in it — even if those words are hard.`, keywords: ['withdrawal', 'avoidance', 'ending', 'closure'] },
  { id: 'ut-08', name: 'Their Potential vs. Their Pattern', meaning: `You are in love with who they could be, not who they are consistently showing up as. Potential is a beautiful, seductive thing — and it is not a foundation. Who someone is on their best day is not a promise of who they'll be on the ordinary ones. What is their pattern? That is your answer.`, keywords: ['projection', 'wishful thinking', 'patterns', 'reality check'] },
  { id: 'ut-09', name: 'The Almost Relationship', meaning: `You were close. You felt it. Something real was building — and then it stopped, or changed, or was never quite defined. Almost relationships carry a specific kind of grief because there's no clear event to mourn. You just… end up without the thing you thought you were building. That grief is valid. Grieve it. Then make space for something that doesn't make you wonder.`, keywords: ['grief', 'unclear endings', 'ambiguity', 'unfinished'] },
  { id: 'ut-10', name: 'Reciprocity', meaning: `Look at who initiates. Who follows up. Who makes the effort to show up when it's inconvenient. Who remembers the small things. Is the energy matched? Love is not supposed to be a one-person job. If you consistently feel like you're doing more, it's because you are. That's information. Use it.`, keywords: ['balance', 'mutual effort', 'energy exchange', 'one-sided'] },
  { id: 'ut-11', name: 'The Rebound', meaning: `Someone is here — but they are using your warmth to thaw out from someone else's cold. That doesn't make them a villain. It makes them human and not ready. The danger is that rebounds feel like love in the early stages, because the intensity is real — it just isn't necessarily about you. Are you the destination or the waystation?`, keywords: ['unhealed', 'transitional', 'readiness', 'not about you'] },
  { id: 'ut-12', name: 'Love Bombing', meaning: `It came in fast and it came in big — the attention, the affection, the declarations. It felt like finally. But intensity at the start of a connection is not the same as depth. Real love builds over time with consistent, humble action. What arrived in a flood can leave the same way. Ask yourself: is this person showing up consistently, or performing for the highlight reel?`, keywords: ['intensity', 'manipulation', 'pace', 'red flags'] },
  { id: 'ut-13', name: 'The Anxious Attachment Loop', meaning: `You reach out, then pull back to check if they'll chase. They don't chase fast enough, so the anxiety spikes. You interpret their normal behavior as rejection and react from that place. They pull back. You reach more. It's a cycle, and it is exhausting for both of you. The loop only breaks when you interrupt your end of it — not by trying harder, but by getting grounded in yourself.`, keywords: ['attachment patterns', 'anxiety', 'self-regulation', 'cycle-breaking'] },
  { id: 'ut-14', name: 'The Test', meaning: `You are testing them — sometimes deliberately, sometimes not. Pulling away to see if they follow. Being vague to see if they'll push for clarity. Starting arguments to see how they handle conflict. Tests are a trauma response, not a connection strategy. The person meant for you shouldn't have to pass a series of trials you haven't told them about. Let them in, or let them go.`, keywords: ['fear of intimacy', 'self-protection', 'vulnerability', 'trust'] },
  { id: 'ut-15', name: 'Avoidant Energy', meaning: `They want connection — in theory. In practice, the moment things get real, they create distance. It might look like being "too busy," or suddenly finding faults, or pulling back right when things start to feel good. Avoidance is not a character flaw; it's usually a wound. But a wound that someone refuses to look at cannot be loved away. You cannot out-love someone's unwillingness to be present.`, keywords: ['avoidant attachment', 'distance', 'intimacy avoidance', 'patterns'] },
  { id: 'ut-16', name: 'The Apology That Changed Nothing', meaning: `They said sorry. They may have even meant it in the moment. But the behavior continued. An apology without behavioral change is just words dressed up as accountability. It's important to notice: do you keep accepting apologies for the same things? Because eventually the apology stops being the issue. The acceptance is.`, keywords: ['accountability', 'patterns', 'change', 'self-worth'] },
  { id: 'ut-17', name: 'The Hot and Cold', meaning: `Intense one week, distant the next. Present and warm, then suddenly cold for no visible reason. The hot and cold dynamic is one of the most destabilizing experiences in connection because your nervous system never gets to relax. You're always preparing for the shift. That is not intimacy. That is survival. You deserve a temperature you can live in.`, keywords: ['inconsistency', 'emotional regulation', 'nervous system', 'stability'] },
  { id: 'ut-18', name: 'Projection', meaning: `Someone is putting something on you that belongs to them — accusing you of the very things they're doing, suspicious of behaviors that mirror their own, assigning motives to you that live in their own history. It's disorienting, because you keep trying to defend yourself against a portrait that isn't you. Stop defending. You know who you are. The painting is theirs.`, keywords: ['projection', 'gaslighting', 'self-knowing', 'others\' wounds'] },
  { id: 'ut-19', name: 'The Jealousy Play', meaning: `Someone is using your feelings for them as leverage — mentioning others to gauge your reaction, creating triangles, making you feel like you have competition you need to rise to. Real love does not require you to perform for an audience. If you feel like you're constantly competing, it's because someone is making you compete. That is a choice they are making. Not a situation you have to play in.`, keywords: ['manipulation', 'insecurity', 'triangulation', 'competition'] },
  { id: 'ut-20', name: 'The Comfort Zone', meaning: `You've been together long enough that comfort replaced intention. The relationship isn't bad — it's just... quiet. The effort that built what you have stopped once you had it. Something needs to be consciously revived here — not with grand gestures, but with the small, deliberate choices to keep choosing each other. Is that something you're both willing to do?`, keywords: ['complacency', 'intentionality', 'long-term love', 'reinvestment'] },
  { id: 'ut-21', name: 'The Walls They Built', meaning: `They want love. They just don't fully believe they can have it, or that it will stay, or that they're worth it when things get hard. The walls aren't about you — they were built long before you arrived. You can be patient. You can be gentle. But you cannot dismantle someone else's walls for them. That is their work. The question is how long you're willing to knock.`, keywords: ['emotional walls', 'past wounds', 'patience limits', 'their work'] },
  { id: 'ut-22', name: 'Emotional Unavailability', meaning: `They are present in body and absent in soul. You can feel the distance even when they're right next to you. The conversations stay surface-level no matter how deep you try to go. Emotional unavailability is not permanent — but it is not something you can fix by being more loving, more patient, more understanding. They have to choose to show up. Have they?`, keywords: ['emotional absence', 'surface-level connection', 'unhealed', 'readiness'] },
  { id: 'ut-23', name: 'The Unsaid Thing', meaning: `There is something neither of you has said out loud yet — a truth that's been living in the silences, in the careful conversations, in the things you almost say and then swallow. This card is asking you to name it. Not to burn everything down, but because unnamed things have enormous power over the shape of a relationship. Say the thing. See what happens.`, keywords: ['communication', 'courage', 'truth-telling', 'unspoken tension'] },
  { id: 'ut-24', name: 'The Sacrifice That Wasn\'t Reciprocated', meaning: `You gave something up — time, energy, a part of yourself — and it wasn't met with equal care on their side. That sacrifice deserves acknowledgment, even if it's just from you to you. You cannot keep donating parts of your life to someone who doesn't notice the cost. Generosity is beautiful. Depletion is not.`, keywords: ['self-sacrifice', 'one-sided', 'resentment', 'self-care'] },
  { id: 'ut-25', name: 'The Fear of Loss', meaning: `You're making choices from the fear of losing them, not from the clarity of what you actually want. Fear-based love stays in situations past their expiration date. It says yes when it means no. It makes itself smaller. Fear of loss is real and understandable — but it is not a strategy. What would you choose if you weren't afraid of losing them?`, keywords: ['fear', 'scarcity mindset', 'choice', 'clarity'] },
  { id: 'ut-26', name: 'Worth the Wait', meaning: `Good things take time. This particular connection may be asking you for patience — not blind patience, but the kind rooted in genuine evidence that something real is being built. Are there consistent signs of care, growth, and intention between you? Then trust the slower pace. Real love doesn't always arrive on your timeline.`, keywords: ['patience', 'trust', 'timing', 'evidence-based hope'] },
  { id: 'ut-27', name: 'The Grand Gesture Trap', meaning: `They showed up with something big — a declaration, a surprise, an impressive move — right when you were about to pull away. And it worked. It bought more time. But notice: the grand gesture arrived right at the edge of your limit. That timing is not coincidence. Love should not require a performance to keep you. Watch what happens after the gesture fades.`, keywords: ['manipulation', 'patterns', 'grand gestures', 'consistency'] },
  { id: 'ut-28', name: 'The Comparison', meaning: `You're being compared — to an ex, to an ideal, to someone else they see as the standard. Or you're doing the comparing. Either way, this card says: stop. Nobody wins in comparison. You are not a consolation prize, and you are not a judge. Every person and every connection is its own thing. Measure this relationship only against what you need and what you deserve.`, keywords: ['comparison', 'self-worth', 'fairness', 'uniqueness'] },
  { id: 'ut-29', name: 'The Gut Feeling', meaning: `Your body has been trying to tell you something for a while now. That tight feeling in your chest when you see their name. The way your shoulders tense instead of relax when you hear from them. The quiet dread that lives just under the hope. Your gut is not dramatic. It is not broken. It is the oldest, wisest part of you, and it is trying to get your attention. Listen.`, keywords: ['intuition', 'body wisdom', 'knowing', 'trust yourself'] },
  { id: 'ut-30', name: 'The Misalignment', meaning: `You want different things — and both of you know it. Maybe one wants a family and the other doesn't. Maybe one is ready to commit and the other needs years of freedom. Maybe the values that seemed similar have revealed themselves to be fundamentally different. Misalignment is not a failure of love. It is a reality of timing, life stage, and direction. Love is sometimes not enough.`, keywords: ['incompatibility', 'life path', 'values', 'hard truths'] },
  { id: 'ut-31', name: 'The Return', meaning: `They're back — or you're considering going back. Before you do anything, get honest: what has actually changed? Not what has been promised. Not what feels possible in this hopeful, charged moment. What has concretely, demonstrably shifted in the dynamic, the behavior, the underlying issue that caused the break? If the answer is "nothing," returning is not a reunion. It's a repeat.`, keywords: ['reconciliation', 'returning', 'what has changed', 'patterns'] },
  { id: 'ut-32', name: 'The Friendship Foundation', meaning: `The romantic feeling may have complicated, faded, or shifted — but underneath it, there is something genuinely real: a friendship, a care, a history that matters. This card asks you to be honest about what form this relationship is actually meant to take in your life. Not every love story is a romance. Some of the deepest loves of our lives are the ones that eventually find their truest shape.`, keywords: ['friendship', 'connection type', 'honest redefinition', 'care'] },
  { id: 'ut-33', name: 'Vulnerability', meaning: `You have been managing yourself in this relationship — carefully editing what you share, keeping the raw, unfiltered version of yourself behind the curtain. The person who loves the curated version doesn't fully know you yet. Real intimacy lives on the other side of the risk of being truly seen. You don't have to share everything at once. But you do have to let them see you, eventually.`, keywords: ['vulnerability', 'authenticity', 'intimacy', 'being seen'] },
  { id: 'ut-34', name: 'The Boundary That Keeps Getting Crossed', meaning: `You've said it. Maybe more than once. And it keeps happening — maybe slightly differently, maybe with a good explanation, but it keeps happening. A boundary that is consistently ignored is a message about how someone views your limits. Take it seriously. Not with anger, but with clarity. What you allow continues.`, keywords: ['boundaries', 'self-respect', 'patterns', 'what you allow'] },
  { id: 'ut-35', name: 'The Healing Connection', meaning: `This person arrived in your life at a time when you needed something to soften — to open up what you had closed off, to remind you that safety in love is possible. This may be exactly what it is: a healing connection. Not necessarily forever, but genuinely significant. Honor what is being healed here, even if the relationship ultimately takes a different form than you hoped.`, keywords: ['healing', 'purpose', 'temporary but real', 'gratitude'] },
  { id: 'ut-36', name: 'The Karmic Pattern', meaning: `You have been here before — not with this person, but in this dynamic. The same emotional landscape, the same push-pull, the same feeling of almost. Karmic patterns repeat until they're learned. What is this situation teaching you that all the previous versions of it have been trying to teach you? The lesson is not about them. It never was.`, keywords: ['karmic patterns', 'repetition', 'soul lessons', 'growth'] },
  { id: 'ut-37', name: 'The Ultimatum', meaning: `Something has reached its edge. A decision needs to be made — by you, by them, or by both. Ultimatums get a bad reputation, but clarity is not a weapon. Knowing what you need and being honest about the limits of your capacity to wait is not manipulation. It is self-knowledge in action. What do you actually need from this situation? And are you willing to hold that line?`, keywords: ['decision point', 'clarity', 'limits', 'self-knowledge'] },
  { id: 'ut-38', name: 'Space That Isn\'t Distance', meaning: `Someone needs room to breathe — it doesn't mean they're pulling away or losing interest. It means they are a person who needs space to process, to restore, to return to themselves before they can fully return to you. Can you hold that without making it mean something it doesn't? Can you give space generously, rather than fearfully?`, keywords: ['space', 'introversion', 'trust', 'not abandonment'] },
  { id: 'ut-39', name: 'Choosing Yourself', meaning: `There comes a moment when the most loving thing you can do — for both of you — is to choose yourself. Not dramatically. Not as a punishment. But with the quiet, firm knowledge that you cannot keep reducing yourself to fit into someone else's story. You are the main character in your own life. Act like it. Choose yourself first and let everything rearrange around that.`, keywords: ['self-first', 'self-love', 'main character energy', 'boundaries'] },
  { id: 'ut-40', name: 'The Unhealed Wound', meaning: `Something they did — or something that was done to them long before you arrived — is running the show right now. Old pain shows up in new relationships wearing present-tense costumes. This card asks: is the wound theirs to heal, or have you been absorbing the impact of someone else's unfinished emotional work? You can have compassion and still have limits.`, keywords: ['trauma', 'healing', 'compassion', 'limits'] },
  { id: 'ut-41', name: 'The Long Game', meaning: `This is a slow build. It doesn't have the intensity of the early stages — it has something quieter and more durable: consistent presence, genuine care, a person who shows up without being asked. The long game isn't romantic in a cinematic way. It is romantic in the way that actually matters: reliably, honestly, over time. Don't mistake steadiness for boring.`, keywords: ['long-term love', 'consistency', 'quiet depth', 'steadiness'] },
  { id: 'ut-42', name: 'The Permission You Keep Waiting For', meaning: `You are waiting for someone — them, a sign, the universe, your past self — to give you permission to leave, to stay, to speak, to love, to let go. That permission was always yours to grant. Nobody is coming to release you. Nobody can give you the signal that it's finally okay. The authority over your own life has always lived in you. Use it.`, keywords: ['permission', 'self-authority', 'decision-making', 'empowerment'] },
  { id: 'ut-43', name: 'The Love That Wasn\'t Enough', meaning: `You loved them. Truly. And it still didn't work. That is one of the hardest truths love teaches us: that love can be real and still not be enough. It doesn't mean you failed. It doesn't mean love is meaningless. It means that love requires timing, readiness, compatibility, and mutual will — and sometimes one of those pieces is missing. You did not love wrong. The pieces just didn't all fit.`, keywords: ['grief', 'love without success', 'acceptance', 'honoring what was real'] },
  { id: 'ut-44', name: 'What You Deserve', meaning: `You have spent so long adjusting to less that you've started to mistake it for normal. Someone who is consistently present. Someone who communicates honestly even when it's uncomfortable. Someone who chooses you not just when it's convenient, but on the Tuesday afternoons when nothing is particularly exciting. That is not a fantasy. That is a standard. Remember what you actually deserve.`, keywords: ['self-worth', 'standards', 'what love looks like', 'raising the bar'] },
];

// Channeled Spreads (3 Tarot + 1 Oracle card)
export const CHANNELED_SPREADS = {
  channeled_where_we_stand: {
    name: "Where We Actually Stand",
    count: 4,
    tarotCount: 3,
    oracleCount: 1,
    positions: ["How They See You", "What's Holding Them Back", "The Honest Energy Between You", "The Unfiltered Truth"],
    channeled: true,
    isChanneled: true,
    description: "3 Tarot cards read the situation. 1 Oracle card delivers the unfiltered message from their energy.",
    category: 'channeled',
  },
  channeled_should_i_reach_out: {
    name: "Should I Reach Out?",
    count: 4,
    tarotCount: 3,
    oracleCount: 1,
    positions: ["Your Energy Right Now", "Their Energy Right Now", "What Would Happen If You Did", "The Oracle's Verdict"],
    channeled: true,
    isChanneled: true,
    description: "Let the cards tell you what they can't — and what you already know deep down.",
    category: 'channeled',
  },
  channeled_message_from_them: {
    name: "The Message They Haven't Sent",
    count: 4,
    tarotCount: 3,
    oracleCount: 1,
    positions: ["What's on Their Heart", "What They're Afraid to Say", "What the Universe Sees", "The Raw Truth"],
    channeled: true,
    isChanneled: true,
    isMessage: true,
    description: "Channel what they haven't put into words yet. First-person voice, no filters.",
    category: 'channeled',
  },
};

// Oracle-Only Spreads (Unfiltered Truth Oracle deck)
export const ORACLE_ONLY_SPREADS = {
  oracle_quick_hit: {
    name: "The Quick Hit",
    count: 1,
    oracleCount: 1,
    positions: ["The Truth Right Now"],
    isOracleOnly: true,
    description: "One card. One truth. No sugarcoating.",
    category: 'oracle',
  },
  oracle_unspoken_truth: {
    name: "Their Unspoken Truth",
    count: 2,
    oracleCount: 2,
    positions: ["What They're Thinking", "What They're Feeling But Won't Say"],
    isOracleOnly: true,
    description: "Two cards from the Unfiltered Truth deck — one for their mind, one for their heart.",
    category: 'oracle',
  },
  oracle_reality_check: {
    name: "The Reality Check",
    count: 3,
    oracleCount: 3,
    positions: ["The Illusion You're Holding", "The Reality", "What You Need to Do With That"],
    isOracleOnly: true,
    description: "Three cards to cut through the story you're telling yourself and get to ground truth.",
    category: 'oracle',
  },
};

export const ORACLE_MESSAGES = [
  { id: 1, title: "Trust the Process", message: "The universe is unfolding exactly as it should. Release your need for control and trust in the divine timing of your journey.", theme: "faith" },
  { id: 2, title: "Inner Light", message: "Your inner radiance is your greatest guide. Turn inward to find the answers you seek — they have always been within you.", theme: "intuition" },
  { id: 3, title: "Sacred Release", message: "What no longer serves your highest good must be released. Let go with grace and make space for the new blessings awaiting you.", theme: "release" },
  { id: 4, title: "Abundance Flows", message: "Open your heart and hands to receive. The universe is abundant and wants to shower you with gifts — allow yourself to accept them.", theme: "abundance" },
  { id: 5, title: "Soul Connection", message: "A meaningful soul connection is drawing near. Be open to recognizing kindred spirits who mirror your own light.", theme: "connection" },
  { id: 6, title: "Creative Spark", message: "Your creative energy is at its peak. Channel this divine inspiration into something beautiful and let your soul express itself freely.", theme: "creativity" },
  { id: 7, title: "Grounding Earth", message: "Return to your roots and ground your energy. Connect with nature, breathe deeply, and remember the strength of the earth beneath you.", theme: "grounding" },
  { id: 8, title: "Transformation", message: "You are in the midst of a powerful transformation. Embrace the changes within you — the caterpillar must dissolve to become the butterfly.", theme: "change" },
  { id: 9, title: "Divine Protection", message: "You are surrounded by divine protection. Your spiritual guides are watching over you. Release fear and walk forward in faith.", theme: "protection" },
  { id: 10, title: "New Dawn", message: "A new chapter is beginning. The old cycle has completed its purpose. Step boldly into the light of this fresh start.", theme: "beginnings" },
  { id: 11, title: "Heart Wisdom", message: "Your heart holds ancient wisdom. When the mind overthinks, return to the heart. It always knows the way forward.", theme: "wisdom" },
  { id: 12, title: "Cosmic Alignment", message: "The stars are aligning in your favor. Pay attention to synchronicities — the universe is sending you signs.", theme: "alignment" },
];