import React from 'react';
import { motion } from 'framer-motion';
import { ScrollText } from 'lucide-react';

export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-16">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-10 text-center">
        <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-secondary mb-4 text-violet">
          <ScrollText className="w-6 h-6" />
        </div>
        <h1 className="font-heading text-3xl sm:text-4xl font-bold mb-3">Terms & Conditions</h1>
        <p className="text-muted-foreground text-sm">Last updated: April 2026</p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="glass-card rounded-2xl p-6 sm:p-10 space-y-8 text-sm leading-relaxed text-foreground/90"
      >
        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">1. Acceptance of Terms</h2>
          <p>By accessing or using Tarotories ("the App"), you agree to be bound by these Terms & Conditions. If you do not agree, please do not use the App.</p>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">2. Entertainment Purposes Only</h2>
          <p className="font-medium text-gold">Important: Tarotories is intended for entertainment and personal reflection purposes only.</p>
          <p>Tarot readings, astrological interpretations, oracle messages, and all other content provided by the App are for entertainment and self-exploration. They are not a substitute for professional advice of any kind, including but not limited to medical, psychological, financial, or legal advice. Do not make major life decisions based solely on content generated by this App.</p>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">3. Eligibility</h2>
          <p>You must be at least 13 years of age to use this App. By using the App, you represent that you meet this requirement.</p>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">4. Account Responsibilities</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately of any unauthorized use.</p>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">5. Subscriptions & Payments</h2>
          <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-2">
            <li>Premium subscriptions are billed on a recurring basis (monthly or annually) via Stripe.</li>
            <li>You may cancel your subscription at any time through your account settings or billing portal.</li>
            <li>Cancellations take effect at the end of the current billing period — no partial refunds are issued.</li>
            <li>We reserve the right to change pricing with reasonable advance notice.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-2">
            <li>Use the App for any unlawful purpose</li>
            <li>Attempt to reverse engineer, scrape, or exploit the App</li>
            <li>Misrepresent your identity or affiliation</li>
            <li>Interfere with the App's normal operation</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">7. Intellectual Property</h2>
          <p>All content, designs, and features of Tarotories are owned by us or our licensors. You may not copy, distribute, or create derivative works without our written permission.</p>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">8. Disclaimer of Warranties</h2>
          <p>The App is provided "as is" without warranties of any kind. We do not guarantee the accuracy, completeness, or usefulness of any reading or content generated by the App.</p>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">9. Limitation of Liability</h2>
          <p>To the fullest extent permitted by law, Tarotories shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the App.</p>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">10. Governing Law</h2>
          <p>These Terms are governed by the laws of the United States. Any disputes shall be resolved in accordance with applicable law.</p>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">11. Changes to Terms</h2>
          <p>We may update these Terms at any time. Continued use of the App after changes constitutes your acceptance of the new Terms.</p>
        </section>

        <section className="space-y-3">
          <h2 className="font-heading text-lg font-semibold text-primary">12. Contact</h2>
          <p>For questions about these Terms, please contact us through the App's support channels.</p>
        </section>
      </motion.div>
    </div>
  );
}